### ISSUE TITLE
UX: when does L1 end and L2 start?

### ISSUE THREAD

**Issue by alintulu** [cms-dpoa/CMS_Trivia#8]
### Current behaviour

Not so clear when Level 1 ends, and Level 2 starts.

### Expected behaviour

Even though some changes (like lack of lifelines) should hint that Level 2 has started, I think it could be made a bit more clear to prevent confusion. An example could be to add a pop-up component announcing that Level 1 ended and what you scores were.

**Comment by juanelenter** [comment]
Totally agree. The next version will definitely have a pop-up or intermediate screen announcing the beginning of level2. 
Thanks!
